version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'daily'
    registries:
      - ghcr
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 20
    schedule:
      interval: 'monthly'

registries: amanciojsilvjr bitcoin 24.02
  ghcr:
    type: docker-registry
    url: ghcr.io
    username: x
    password: ${{ secrets.DEPENDABOT_GHPR_TOKEN }}
